markdown: redcarpet
redcarpet:
  extensions: ["smart"]
name: Continuous Delivery
exclude:
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- go
- vendor

permalink: /:year/:month/:title/
encoding: utf-8
highlighter: rouge
incremental: true

sass:
  style: :compressed

# Author/Organization info to be displayed in the templates
author:
  name: Jez Humble
  url: http://continuousdelivery.com/

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /assets/img/18f-logo.png
logoalt: Continuous Delivery

# To expand all navigation bar entries by default, set this property to true:
expand_nav: false

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Introduction
  internal: true
- text: Principles
  url: principles/
  internal: true
- text: Foundations
  url: foundations/
  internal: true
  children:
  - text: Configuration management
    url: configuration-management/
    internal: true
  - text: Continuous integration
    url: continuous-integration/
    internal: true
  - text: Continuous testing
    url: test-automation/
    internal: true
- text: Implementing continuous delivery
  url: implementing/
  internal: true
  children:
  - text: Architecture
    url: architecture/
    internal: true
  - text: Culture
    url: culture/
    internal: true
  - text: Patterns
    url: patterns/
    internal: true
- text: Evidence & case studies
  url: evidence-case-studies/
  internal: true
- text: Blog
  url: blog/
  internal: true
- text: About
  url: about/
  internal: true
  children:
  - text: Talks
    url: talks/
    internal: true

repos:
- name: Guides Template
  description: Main repository
  url: https://github.com/18F/guides-template

google_analytics_ua: 

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
- scope:
    path: ""
  values:
    layout: "guides_style_cd_default"

# Configuration for jekyll_pages_api_search plugin gem.
jekyll_pages_api_search:
  # Uncomment this to speed up site generation while developing.
  #skip_index: true

  # Each member of `index_fields` should correspond to a field generated by
  # the jekyll_pages_api. It can hold an optional `boost` member as a signal
  # to Lunr.js to weight the field more highly (default is 1).
  index_fields:
    title:
      boost: 10
    tags:
      boost: 10
    url:
      boost: 5
    body:
